### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by daitr616** [barbeque/static-image-to-gif#1]
When I run the code by using "python3 gifify.py" I get errors：
Traceback (most recent call last):
  File "gifify.py", line 73, in <module>
    writeGif("output.gif", [Image.open(fn) for fn in filenames], duration=0.1)
  File "./vendor\images2gif.py", line 562, in writeGif
    images, xy = gifWriter.handleSubRectangles(images, subRectangles)
  File "./vendor\images2gif.py", line 300, in handleSubRectangles
    images, xy = self.getSubRectangles(images)
  File "./vendor\images2gif.py", line 352, in getSubRectangles
    im2 = im[y0:y1,x0:x1]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by barbeque** [comment]
It looks like there's [a newer version of images2gif](https://github.com/isaacgerg/images2gif/blob/master/images2gif.py); could you please try swapping that out and see if it fixes the problem?
